# Generated by Django 5.1.4 on 2024-12-08 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Senha', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=80)),
                ('Descricao', models.TextField()),
                ('Data_Criacao', models.DateTimeField(auto_now_add=True)),
                ('Data_Limite', models.DateTimeField()),
                ('Status', models.BooleanField(default=False)),
                ('Atribuido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.user')),
            ],
        ),
    ]
